android.useAndroidX=true
android.nonTransitiveRClass=true

org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

# 本机 Clash 代理(依赖下载用)
systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=7897
systemProp.http.nonProxyHosts=localhost|127.0.0.1